FROM node:22-alpine AS base

RUN npm install -g pnpm
WORKDIR /app
COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./
COPY services/rewrite-api/package.json ./services/rewrite-api/
RUN pnpm install --filter rewrite-api...
COPY services/rewrite-api ./services/rewrite-api

EXPOSE 3003

CMD ["pnpm", "--filter", "rewrite-api", "run", "dev"]
