FROM node:22-alpine AS base

RUN npm install -g pnpm
WORKDIR /app
COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./
COPY services/jd-analyzer-api/package.json ./services/jd-analyzer-api/
RUN pnpm install --filter jd-analyzer-api...
COPY services/jd-analyzer-api ./services/jd-analyzer-api

EXPOSE 3002

CMD ["pnpm", "--filter", "jd-analyzer-api", "run", "dev"]
