FROM node:22-alpine AS base

RUN npm install -g pnpm
WORKDIR /app
COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./
COPY frontend/package.json ./frontend/
RUN pnpm install --filter frontend...
COPY frontend ./frontend

EXPOSE 3000

CMD ["pnpm", "--filter", "frontend", "run", "dev"]
